services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" 
    volumes:
      - ./static:/usr/share/nginx/html # portainer relative paths test
      - /mnt/stacks/shared/page.html:/usr/share/nginx/html/page.html # check if absolute paths are loading files from host
    deploy:
      mode: replicated
      replicas: 1
